### ISSUE TITLE
Detected integration that called async_setup_platforms

### ISSUE THREAD

**Issue by Jefe2** [ehendrix23/hass_myq#148]
## Version of the custom_component
MyQ v1.0.0rc3
HA Core version 2023.2.4

## Describe the bug

Log generates this message:

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for myq using this method at custom_components/myq/__init__.py, line 53: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

## Debug log

```text


```

**Comment by gongtao0607** [comment]
myq refuse to run on HA 20230503.1

Logger: homeassistant.config_entries
Source: custom_components/myq/__init__.py:53
Integration: MyQ
First occurred: 11:01:46 PM (1 occurrences)
Last logged: 11:01:46 PM

Error setting up entry xxxxxxxx@gmail.com for myq
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/myq/__init__.py", line 53, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by ehendrix23** [comment]
Please use the standard MyQ integration in Home Assistant.
